
sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test
- npm run coveralls
- npm run docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master    
before_deploy:
  - touch .nojekyll
  - sed -i '/docs' .gitignore